Task2
Larten13/GamesFinder pull request #2
Opened 2022-05-11 10:34 UTC by Larten13

добавлен recyclerView, создан адаптер для него, созданы моковые данные для отрисовки recyclerView

2022-05-11 20:31 UTC, AlexeyGvozdev commented
Название пулреквеста

2022-05-11 20:37 UTC, AlexeyGvozdev requested changes

2022-05-11 20:37 UTC, AlexeyGvozdev commented on app/src/main/java/com/larten/android/gamesfinder/GenresAdapter.kt
> +    private val dataset: List<Genre>
у тебя сейчас получается не изменяемый список в адаптере

2022-05-11 20:37 UTC, AlexeyGvozdev commented on app/src/main/java/com/larten/android/gamesfinder/GenresAdapter.kt
> +        holder.textView.text = item.name
давай это уберём во вьюхолдер

2022-05-11 20:37 UTC, AlexeyGvozdev commented on app/src/main/java/com/larten/android/gamesfinder/MockDataGenres.kt
> +            Genre(4, "Action", "action", 149007, R.drawable.ic_action),
В место R.drawable.ic_action давай будем урл использовать. Во вьюхолдере надо будет качать картинки

2022-05-11 20:37 UTC, AlexeyGvozdev commented on app/src/main/res/layout/finder_fragment.xml
> +    <SearchView
searchview добавляем в другой задаче

2022-05-12 08:06 UTC, Larten13 commented on app/src/main/java/com/larten/android/gamesfinder/GenresAdapter.kt
> +    private val dataset: List<Genre>
List заменил на MutableList

2022-05-14 19:45 UTC, closed without merging